app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: true
  swagger.enabled: false
  firebase:
    CredentialsFileAndroid: "/root/app/certs/sira-firebase-service-account.json"
    CredentialsFileAndroidV2: "/root/app/certs/sira-firebase-service-account.json"
    CredentialsFileIOS: "/root/app/certs/sira-firebase-service-account.json"
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: sira-dev
  mongo:
    hosts:
      - root:root_mongodb@194.233.84.28:27017/?compressors=snappy,zlib,zstd
  files:
    BaseOutputPath: "/root/app/t2v-out"
  animatelcm:
    Endpoint: http://localhost:8080
    InferPath: /api/v1/infer/animate_lcm
  asynq:
    Addr: 194.233.85.239:6379
    Password: braly@123
    DB: 1
    Queues:
      t2v_default: 10
    Worker:
      Concurrency: 1
