app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: true
  swagger.enabled: false
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://dev.storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: text-to-video
  files:
    BaseOutputPath: "/root/app/t2v-out"
  animatelcm:
    Endpoint: http://localhost:8080
    InferPath: /api/v1/infer/animate_lcm
  asynq:
    Addr: 194.233.92.153:6379
    Password: braly@123
    DB: 1
    Queues:
      t2v_default: 10
    Worker:
      Concurrency: 1
