app:
  port: 8083
  logging:
    development: true
    JsonOutputMode: false
  swagger.enabled: false
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://dev.storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: text-to-video
  files:
    BaseOutputPath: "/home/liam/Downloads/t2v-output"
  animatelcm:
    Endpoint: http://localhost:8082
    InferPath: /api/v1/infer/animatelcm
  asynq:
    Addr: localhost:6379
    Password: braly@123
    DB: 1
    Queues:
      t2v_default: 10
    Worker:
      Concurrency: 10
