app:
  port: 8083
  logging:
    development: true
    JsonOutputMode: false
  swagger.enabled: false
  firebase:
    CredentialsFileAndroid: "/home/liam/Documents/sira/dev/sira-firebase-service-account.json"
    CredentialsFileAndroidV2: "/home/liam/Documents/sira/dev/sira-firebase-service-account.json"
    CredentialsFileIOS: "/home/liam/Documents/sira/dev/sira-firebase-service-account.json"
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://dev.storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: text-to-video
  files:
    BaseOutputPath: "/home/liam/Downloads/t2v-output"
  animatelcm:
    Endpoint: http://localhost:8082
    InferPath: /api/v1/infer/animatelcm
  mongo:
    hosts:
      - root:root_mongodb@194.233.84.28:27017/?compressors=snappy,zlib,zstd
  asynq:
    Addr: localhost:6379
    Password: braly@123
    DB: 1
    Queues:
      t2v_default: 10
    Worker:
      Concurrency: 1
