app:
  port: 8081
  logging:
    development: true
    JsonOutputMode: false
  swagger.enabled: false
  firebase:
    CredentialsFileAndroid: "/root/app/certs/sira-firebase-service-account.json"
    CredentialsFileAndroidV2: "/root/app/certs/sira-android-firebase-service-account.json"
    CredentialsFileIOS: "/root/app/certs/sira-ios-firebase-service-account.json"
    CredentialsFileIOSV2: "/root/app/certs/sira-ios-firebase-service-account-v2.json"
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: sira
  files:
    BaseOutputPath: "/root/app/t2v-out"
  animatelcm:
    Endpoint: http://localhost:8080
    InferPath: /api/v1/infer/animate_lcm
  asynq:
    Addr: 94.72.114.19:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
    Queues:
      t2v_default: 10
    Worker:
      Concurrency: 2
