app:
  port: 8080
  tls:
    Enabled: false
    CertFile: "/home/ssl/fullchain.pem"
    KeyFile: "/home/ssl/privkey.pem"
  firebase:
    CredentialsFile: "/home/ssl/sira-firebase-service-account.json"
  logging:
    development: true
  swagger.enabled: true
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: sira
  asynq:
    Addr: 94.72.114.19:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
