app:
  port: 8080
  tls:
    Enabled: false
    CertFile: "/home/ssl/fullchain.pem"
    KeyFile: "/home/ssl/privkey.pem"
  middlewares:
    AuthenticationEnable: false
  firebase:
    CredentialsFileAndroid: "/home/ssl/sira-firebase-service-account.json"
    CredentialsFileAndroidV2: "/home/ssl/sira-firebase-service-account.json"
    CredentialsFileIOS: "/home/ssl/sira-ios-firebase-service-account.json"
  logging:
    development: true
  swagger.enabled: true
  minio:
    Endpoint: dev.storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: uCCpbIoWR4ddYi1I94MS
    SecretAccessKey: w3Ydr8YTSwJxtcl9H9NrTK8oI0EF4yR77VPY0zMu
    UseSSL: false
    BucketName: sira
  mongo:
    hosts:
      - root:root_mongodb@194.233.84.28:27017/?compressors=snappy,zlib,zstd
  asynq:
    Addr: 194.233.85.239:6379
    Password: braly@123
    DB: 1
