app:
  port: 8080
  tls:
    Enabled: false
    CertFile: "/home/ssl/fullchain.pem"
    KeyFile: "/home/ssl/privkey.pem"
  middlewares:
    AuthenticationEnable: false
  firebase:
    CredentialsFileAndroid: "/home/ssl/sira-firebase-service-account.json"
    CredentialsFileAndroidV2: "/home/ssl/sira-firebase-service-account.json"
    CredentialsFileIOS: "/home/ssl/sira-ios-firebase-service-account.json"
    CredentialsFileIOSV2: "/home/ssl/sira-ios-firebase-service-account.json"
  logging:
    development: true
  swagger.enabled: true
  minio:
    Endpoint: storage.bralyvn.com
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: true
    BucketName: sira-dev
  mongo:
    hosts:
      - root:root_mongodb@194.233.84.28:27017/?compressors=snappy,zlib,zstd
  asynq:
    Addr: 194.233.85.239:6379
    Password: braly@123
    DB: 1
