app:
  models.data:
    - ID: amnd_pixar
      TriggerWords:
    - ID: amnd_realistic
      TriggerWords: RAW photo, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3
    - ID: amnd_pixel
      TriggerWords: pixel art, pixel art style
    - ID: amnd_anime
      TriggerWords: high res
    - ID: amnd_vangogh
      TriggerWords: lvngvncnt
    - ID: amnd_general
      TriggerWords:
