app:
  port: 8080
  tls:
    Enabled: false
    CertFile: "/app/ssl/fullchain.pem"
    KeyFile: "/app/ssl/privkey.pem"
  logging:
    development: true
  swagger.enabled: true
  minio:
    Endpoint: 94.72.114.16
    PublicEndpoint: https://storage.bralyvn.com
    AccessKeyID: I2TCgnjRBzblw6rP50sO
    SecretAccessKey: T9tKE6lCGDWBUnijwjt2V324tBa6x0joVSzza3OG
    UseSSL: false
    BucketName: sira
  asynq:
    Addr: 10.0.0.2:6379
    Password: 2V324tBa6x0joVSzza3OG
    DB: 1
